language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_docs.txt
  - pip install -e .

# command to run tests
script:
  - pytest

after_success:
  - cd docs && make html

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
  github-token: $GITHUB_TOKEN
  local-dir: docs/build/html
  committer-from-gh: true
